name: Build and deploy Node.js apps to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js version for client
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install client dependencies and build
        working-directory: ProyectoBlog/client
        run: |
          npm install
          npm run build --if-present

      - name: Deploy client to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-client'  # Nombre de la aplicación en Azure para el cliente
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: ProyectoBlog/client

  build-and-deploy-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js version for api
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install api dependencies and build
        working-directory: ProyectoBlog/api
        run: |
          npm install
          npm run build --if-present

      - name: Deploy api to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-api'  # Nombre de la aplicación en Azure para la API
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: ProyectoBlog/api
