name: Construir y desplegar aplicaciones Node.js en Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  construir-y-desplegar-cliente:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener código
        uses: actions/checkout@v2
      
      - name: Configurar versión de Node.js para el cliente
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias del cliente
        working-directory: ProyectoBlog/client
        run: yarn install

      - name: Construir cliente
        working-directory: ProyectoBlog/client
        run: yarn build

      - name: Desplegar cliente en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-client'  # Nombre de la aplicación en Azure para el cliente
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: ProyectoBlog/client

  construir-y-desplegar-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener código
        uses: actions/checkout@v2
      
      - name: Configurar versión de Node.js para la API
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias de la API
        working-directory: ProyectoBlog/api
        run: yarn install

      - name: Construir API
        working-directory: ProyectoBlog/api
        run: yarn build

      - name: Desplegar API en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-api'  # Nombre de la aplicación en Azure para la API
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: ProyectoBlog/api
