name: Construir y desplegar aplicaciones Node.js en Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  construir-y-desplegar-cliente:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4
      
      - name: Configurar versión de Node.js para el cliente
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalar dependencias del cliente
        working-directory: client
        run: npm install

      - name: Construir cliente
        working-directory: client
        run: npm run build --if-present

      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4754398BA287499E91E3FEDE9A1F47AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7ED18A61995F43078382E6AB75DBBCB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_337D4250E0224E50B172EDA757AA3515 }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}
          enable-AzPSSession: true

      - name: Desplegar cliente en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-client'  # Nombre de la aplicación en Azure para el cliente
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: client

  construir-y-desplegar-api:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4
      
      - name: Configurar versión de Node.js para la API
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalar dependencias de la API
        working-directory: api
        run: npm install

      - name: Construir API
        working-directory: api
        run: npm run build --if-present

      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4754398BA287499E91E3FEDE9A1F47AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7ED18A61995F43078382E6AB75DBBCB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_337D4250E0224E50B172EDA757AA3515 }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}
          enable-AzPSSession: true

      - name: Desplegar API en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogreact-api'  # Nombre de la aplicación en Azure para la API
          slot-name: 'Production'  # Nombre del slot en Azure si aplica
          package: api
